universe	      = vanilla
executable            = cmsRun.sh
arguments             = $(ProcId) fileList.txt $(ClusterId) $(ProcId)
output                = ../output/PFCandInfo.$(ClusterId).$(ProcId).out
error                 = ../error/PFCandInfo.$(ClusterId).$(ProcId).err
log                   = ../log/PFCandInfo.$(ClusterId).log
when_to_transfer_output = ON_EXIT
should_transfer_files = YES
+JobFlavour = "testmatch"
queue 7