universe	      = vanilla
executable            = sortTrees.sh
arguments             = $(ProcId) $(ClusterId)
output                = ../output/sortTrees.$(ClusterId).$(ProcId).out
error                 = ../error/sortTrees.$(ClusterId).$(ProcId).err
log                   = ../log/sortTrees.$(ClusterId).log
when_to_transfer_output = ON_EXIT
should_transfer_files = YES
+JobFlavour = "longlunch"
queue 16