universe	      = vanilla
executable            = createTreePU_noPU.sh
arguments             = $(ProcId) $(ClusterId) $(ProcId)
output                = ../output/createTreePU_noPU.$(ClusterId).$(ProcId).out
error                 = ../error/createTreePU_noPU.$(ClusterId).$(ProcId).err
log                   = ../log/createTreePU_noPU.$(ClusterId).log
when_to_transfer_output = ON_EXIT
should_transfer_files = YES
+JobFlavour = "longlunch"
queue 16